### ISSUE TITLE
폰트에 대해서 질문이 있습니다.

### ISSUE THREAD

**Issue by op06072** [yf-dev/majsoul-plus-korean#18]
제가 작혼플러스를 찬찬히 뜯어보다 koa서버에서 돌아가고 일렉트론으로 띄우는 것을 보고 작혼플러스를 실행한 컴퓨터의 ip:8887로 접근하여 모바일로 구동하는데는 성공하였습니다. 그러나 게임내부 메인화면의 순위 정보등이나 게임내의 역의 글자가 검은 박스로 나타나는 현상을 발견하였습니다. 컴퓨터에서 구동시 문제가 없는 듯한데 폰트가 어떠한 방식으로 적용되는 것인가요?

**Comment by rishubil** [comment]
아마 폰트 파일을 불러오는 데에 실패하여 그런 현상이 나타나는 것 같습니다.
폰트 파일을 불러오는 데에 실패한 원인이 바로 예상되지는 않지만, 다음 파일들이 정상적으로 불러와졌는지 확인해보시는 것이 좋을 것 같습니다.

- `bitmapfont/en/en_hanyi.fnt`
- `bitmapfont/en/en_haolong.fnt`
- `bitmapfont/en/en_shuhun.fnt`
- `res/atlas/bitmapfont/en.atlas`
- `res/atlas/bitmapfont/en.png`

---

작혼은 내부적으로 [Bitmap Font Generator](http://www.angelcode.com/products/bmfont/doc/file_format.html)의 Format으로 폰트를 사용합니다.

본 한국어 리소스팩은 [FontBM](https://github.com/vladimirgamalyan/fontbm)이라는 Bitmap Font Generator와 호환되는 폰트 생성 유틸리티를 통해 한글 폰트 데이터를 생성하고, 이를 기존 작혼에서 사용하고 있는 폰트 리소스와 바꿔 한글 폰트를 사용합니다.

실제 폰트 생성 과정은 다음과 같습니다.

1. po 파일로부터 번역된 문자열을 실제 대상 문자열이 존재하는 json, csv 파일에 적절하게 적용합니다.
2. 게임에서 사용하는 json, csv 등에서 사용하는 한글 글리프를 [extract_chars.py](https://github.com/yf-dev/majsoul-plus-korean/blob/master/data/src/extract_chars.py)를 통해 모두 수집합니다.
3. [generate_fonts.py](https://github.com/yf-dev/majsoul-plus-korean/blob/master/data/src/generate_fonts.py)에서 수집된 글리프에 대한 폰트 데이터를 FontBM을 사용하여 생성하고, 작혼이 사용하는 형태에 맞게 약간 수정합니다.
4. 생성된 폰트 데이터를 리소스팩 정보 파일(resourcepack.json)에 변경 대상으로 지정합니다.


실제 리소스팩의 전체 변환 과정을 확인하고 싶으시다면 아래 부분 코드를 참조하세요.
https://github.com/yf-dev/majsoul-plus-korean/blob/master/data/src/interface.py#L119-L158

**Comment by rishubil** [comment]
그리고 조금 다른 주제지만, 단순히 모바일에서 작혼을 한국어로 즐기시고 싶다면
아래와 같은 작혼 한국어 리소스 팩의 유저스크립트 버전이 있습니다.

https://openuserjs.org/scripts/rishubil/Majsoul_Korean_(EN_Server)

공식적으로 본 리소스 팩에서 관리하는 기능은 아니고 테스트 수준의 결과물이지만
위 유저스크립트를 사용하면 모바일 환경에서도 한국어로 작혼을 즐길 수 있습니다.

안드로이드에서 유저스크립트 사용 방법은 다음 링크를 참조하세요.
https://gall.dcinside.com/board/view?id=majak&no=392502

(iOS에서도 유저스크립트를 지원하는 브라우저에서는 동작할 것으로 예상되지만, 직접 확인하지는 못했습니다.)

**Comment by op06072** [comment]
그 작혼플러스의 보이스도 이용의 이유거든요

**Comment by rishubil** [comment]
가독성을 위해 이슈 #20 에 올려주신 내용을 그대로 다시 작성합니다.

> ![Screenshot_20200728-001617_Samsung Internet.jpg](https://user-images.githubusercontent.com/60420877/88616061-1d33dd00-d0ce-11ea-94c9-21f5b64839c7.jpg)
![Screenshot_20200727-235812_Samsung Internet.jpg](https://user-images.githubusercontent.com/60420877/88616108-3472ca80-d0ce-11ea-928d-e6e6c6d1fdf2.jpg)![Screenshot_20200727-233237_Samsung Internet.jpg](https://user-images.githubusercontent.com/60420877/88616117-3f2d5f80-d0ce-11ea-8378-1894cf1676d7.jpg)
이런식으로 폰트이슈가 발생합니다. 작혼플러스를 컴에 구동하고 koa서버로 돌고있는 작혼에 컴의 ip주소를 이용해 접속한 것입니다.

**Comment by rishubil** [comment]
위에서도 말씀드렸지만, 아래 파일이 정상적으로 로드되는걸 확인하셨나요?

- `bitmapfont/en/en_hanyi.fnt`
- `bitmapfont/en/en_haolong.fnt`
- `bitmapfont/en/en_shuhun.fnt`
- `res/atlas/bitmapfont/en.atlas`
- `res/atlas/bitmapfont/en.png`

**Comment by op06072** [comment]
> 위에서도 말씀드렸지만, 아래 파일이 정상적으로 로드되는걸 확인하셨나요?
> 
> * `bitmapfont/en/en_hanyi.fnt`
> * `bitmapfont/en/en_haolong.fnt`
> * `bitmapfont/en/en_shuhun.fnt`
> * `res/atlas/bitmapfont/en.atlas`
> * `res/atlas/bitmapfont/en.png`

![image](https://user-images.githubusercontent.com/60420877/88620418-f4651500-d0d8-11ea-8fe9-40c89c723629.png)
개발자 탭에서는 현재 말씀주신 리소스들이 로드되고 있음을 확인하였습니다. 다만 이것은 컴으로 구동된것을 확인한 것인데 모바일은 어떻게 확인하나요?

**Comment by op06072** [comment]
> 위에서도 말씀드렸지만, 아래 파일이 정상적으로 로드되는걸 확인하셨나요?
> 
> * `bitmapfont/en/en_hanyi.fnt`
> * `bitmapfont/en/en_haolong.fnt`
> * `bitmapfont/en/en_shuhun.fnt`
> * `res/atlas/bitmapfont/en.atlas`
> * `res/atlas/bitmapfont/en.png`

![image](https://user-images.githubusercontent.com/60420877/88621286-021b9a00-d0db-11ea-965c-437aa430c59e.png)
안드로이드에서도 로드되고 있습니다.

**Comment by rishubil** [comment]
> 개발자 탭에서는 현재 말씀주신 리소스들이 로드되고 있음을 확인하였습니다.

해당 리소스는 원본 리소스에서도 사용하는 내용이니, 동일한 파일명의 파일들은 리소스팩을 사용하지 않아도 로드됩니다.
파일명만이 아니라 실제 리소스팩에서 교체한 파일 내용으로 로딩되었는지 확인해보셔야 할겁니다.

> 다만 이것은 컴으로 구동된것을 확인한 것인데 모바일은 어떻게 확인하나요?
안드로이드에서도 로드되고 있습니다.

사용하시는 브라우저에 따라 디버깅 툴을 사용하는 방법이 다릅니다.
안드로이드에서 크롬 브라우저를 사용중이시라면, 다음 링크의 내용을 참조해보세요.
https://developers.google.com/web/tools/chrome-devtools/remote-debugging?hl=ko

**Comment by op06072** [comment]
혹시 en.png 안드로이드쪽 모양이 달라보이는게 관련있을까요?

**Comment by op06072** [comment]
> > 개발자 탭에서는 현재 말씀주신 리소스들이 로드되고 있음을 확인하였습니다.
> 
> 해당 리소스는 원본 리소스에서도 사용하는 내용이니, 동일한 파일명의 파일들은 리소스팩을 사용하지 않아도 로드됩니다.
> 파일명만이 아니라 실제 리소스팩에서 교체한 파일 내용으로 로딩되었는지 확인해보셔야 할겁니다.
> 
> > 다만 이것은 컴으로 구동된것을 확인한 것인데 모바일은 어떻게 확인하나요?
> > 안드로이드에서도 로드되고 있습니다.
> 
> 사용하시는 브라우저에 따라 디버깅 툴을 사용하는 방법이 다릅니다.
> 안드로이드에서 크롬 브라우저를 사용중이시라면, 다음 링크의 내용을 참조해보세요.
> https://developers.google.com/web/tools/chrome-devtools/remote-debugging?hl=ko

교체되었는지 확인은 어떤식으로 하면 될까요?

**Comment by rishubil** [comment]
> 혹시 en.png 안드로이드쪽 모양이 달라보이는게 관련있을까요?

관련이 있을 것 같은데... 모양이 구체적으로 어떻게 달라보이나요?

> 교체되었는지 확인은 어떤식으로 하면 될까요?

크롬 개발자 도구의 네트워크 탭에서 확인할 수 있는 컨텐츠의 내용을 리소스 팩의 실제 파일 내용과 비교하시면 될것 같습니다.
사실 제가 지금 직접 확인을 할 수는 없어서 100% 확신할 수는 없지만... 아마 방법은 맞을겁니다 :sweat_smile:

**Comment by op06072** [comment]
> > 혹시 en.png 안드로이드쪽 모양이 달라보이는게 관련있을까요?
> 
> 관련이 있을 것 같은데... 모양이 구체적으로 어떻게 달라보이나요?
> 
> > 교체되었는지 확인은 어떤식으로 하면 될까요?
> 
> 크롬 개발자 도구의 네트워크 탭에서 확인할 수 있는 컨텐츠의 내용을 리소스 팩의 실제 파일 내용과 비교하시면 될것 같습니다.
> 사실 제가 지금 직접 확인을 할 수는 없어서 100% 확신할 수는 없지만... 아마 방법은 맞을겁니다

일단 5개 다 다운은 받았습니다. 이걸 어떻게 확인해보죠?

**Comment by rishubil** [comment]
내려받으셨다는 것들이 모바일 브라우저에서 불러온 파일 내용을 디버깅을 위한 PC로 내려받았다는 것으로 이해하면 될까요?
내려받으신 파일들과 리소스팩의 파일들을 비교하시려면 png 파일은 이미지 뷰어로 열어보면 바로 아실 것 같고,
나머지 파일들은 plain text이니 아무 텍스트 에디터로 열어서 비교해보실 수 있을겁니다.

**Comment by op06072** [comment]
> > 혹시 en.png 안드로이드쪽 모양이 달라보이는게 관련있을까요?
> 
> 관련이 있을 것 같은데... 모양이 구체적으로 어떻게 달라보이나요?
> 
> > 교체되었는지 확인은 어떤식으로 하면 될까요?
> 
> 크롬 개발자 도구의 네트워크 탭에서 확인할 수 있는 컨텐츠의 내용을 리소스 팩의 실제 파일 내용과 비교하시면 될것 같습니다.
> 사실 제가 지금 직접 확인을 할 수는 없어서 100% 확신할 수는 없지만... 아마 방법은 맞을겁니다 :sweat_smile:

모양이 다르단건 그 로드덜되면 사진 파일들은 미리보기에서 초록색으로 나타나는 것같이 그런거 있지않습니까? 그런게 밑에 사진의 en.png의 썸네일?로 나타나서요.

**Comment by op06072** [comment]
> 내려받으셨다는 것들이 모바일 브라우저에서 불러온 파일 내용을 디버깅을 위한 PC로 내려받았다는 것으로 이해하면 될까요?
> 내려받으신 파일들과 리소스팩의 파일들을 비교하시려면 png 파일은 이미지 뷰어로 열어보면 바로 아실 것 같고,
> 나머지 파일들은 plain text이니 아무 텍스트 에디터로 열어서 비교해보실 수 있을겁니다.

그렇군요. 그 png파일은 사람눈으로 보기엔 동일합니다. 외출할일이 있어 나머진 한시간정도 후에 확인 가능할듯합니다.

**Comment by rishubil** [comment]
만약 png 파일을 제외한 다른 파일들도 리소스 팩에 정의한 내용과 동일하다고 하면,
문제의 원인를 간단히 대화로 확인하기는 어려울 것 같습니다.

실제로 작혼이 사용하고 있는 Laya 엔진의 버그인지, 작혼 Plus의 버그인지, 한국어 리소스 팩의 버그인지 알기 어려우므로
모바일 브라우저용 개발자 도구를 통해 천천히 디버깅을 해야할 필요가 있어 보입니다.

다만 제가 직접 해당 이슈에 대해 시간 할애를 하기 어려워
이렇게 글로만 말씀드리는 점에 대해서는 양해해 주시기 바랍니다. :cry:

**Comment by op06072** [comment]
> 만약 png 파일을 제외한 다른 파일들도 리소스 팩에 정의한 내용과 동일하다고 하면,
> 문제의 원인를 간단히 대화로 확인하기는 어려울 것 같습니다.
> 
> 실제로 작혼이 사용하고 있는 Laya 엔진의 버그인지, 작혼 Plus의 버그인지, 한국어 리소스 팩의 버그인지 알기 어려우므로
> 모바일 브라우저용 개발자 도구를 통해 천천히 디버깅을 해야할 필요가 있어 보입니다.
> 
> 다만 제가 직접 해당 이슈에 대해 시간 할애를 하기 어려워
> 이렇게 글로만 말씀드리는 점에 대해서는 양해해 주시기 바랍니다. :cry:

네네 이정도로도 감사합니다. 그 집에 가면 한글 리소스팩을 비활성화 후 모바일 접속을 해보겠습니다.

**Comment by op06072** [comment]
> 만약 png 파일을 제외한 다른 파일들도 리소스 팩에 정의한 내용과 동일하다고 하면,
> 문제의 원인를 간단히 대화로 확인하기는 어려울 것 같습니다.
> 
> 실제로 작혼이 사용하고 있는 Laya 엔진의 버그인지, 작혼 Plus의 버그인지, 한국어 리소스 팩의 버그인지 알기 어려우므로
> 모바일 브라우저용 개발자 도구를 통해 천천히 디버깅을 해야할 필요가 있어 보입니다.
> 
> 다만 제가 직접 해당 이슈에 대해 시간 할애를 하기 어려워
> 이렇게 글로만 말씀드리는 점에 대해서는 양해해 주시기 바랍니다.

![image](https://user-images.githubusercontent.com/60420877/88640933-7cf3ad80-d0f9-11ea-8818-73b3d8b14ed1.png)
이 4가지의 문제로 보입니다.
https://docs.unity3d.com/kr/2018.4/Manual/webgl-browsercompatibility.html 라네요.

**Comment by op06072** [comment]
> 만약 png 파일을 제외한 다른 파일들도 리소스 팩에 정의한 내용과 동일하다고 하면,
> 문제의 원인를 간단히 대화로 확인하기는 어려울 것 같습니다.
> 
> 실제로 작혼이 사용하고 있는 Laya 엔진의 버그인지, 작혼 Plus의 버그인지, 한국어 리소스 팩의 버그인지 알기 어려우므로
> 모바일 브라우저용 개발자 도구를 통해 천천히 디버깅을 해야할 필요가 있어 보입니다.
> 
> 다만 제가 직접 해당 이슈에 대해 시간 할애를 하기 어려워
> 이렇게 글로만 말씀드리는 점에 대해서는 양해해 주시기 바랍니다.

브라우저를 가리는 듯합니다. 파이어폭스로 접속하니 보입니다. 삼성 인터넷 브라우저와 크롬은 여전히 그렇습니다.

**Comment by rishubil** [comment]
정리해주신 내용을 보니 폰트 아틀라스 이미지의 가로 크기가 2의 제곱수로 딱 떨어지지 않도록 되어있는데,
그부분이 문제일 수도 있겠다는 생각이 드네요.

한번 폰트 이미지 크기를 2의 제곱수로 만들고 테스트 해봐야겠습니다.

**Comment by rishubil** [comment]
cfa1ae494a3a6e16cb0f998ecf081988435df232 에서 폰트 아틀라스 이미지의 크기를 수정했습니다.

아래 링크에서 해당 수정 사항이 적용된 리소스 팩을 내려받으실 수 있습니다.
https://github.com/yf-dev/majsoul-plus-korean/releases/tag/3.0.20200728151609

아마도 해당 이슈가 해결됬을 것 같은데, 확인 부탁드립니다.

**Comment by op06072** [comment]
> [cfa1ae4](https://github.com/yf-dev/majsoul-plus-korean/commit/cfa1ae494a3a6e16cb0f998ecf081988435df232) 에서 폰트 아틀라스 이미지의 크기를 수정했습니다.
> 
> 아래 링크에서 해당 수정 사항이 적용된 리소스 팩을 내려받으실 수 있습니다.
> https://github.com/yf-dev/majsoul-plus-korean/releases/tag/3.0.20200728151609
> 
> 아마도 해당 이슈가 해결됬을 것 같은데, 확인 부탁드립니다.

지금 확인해보겠습니다.

**Comment by op06072** [comment]
> [cfa1ae4](https://github.com/yf-dev/majsoul-plus-korean/commit/cfa1ae494a3a6e16cb0f998ecf081988435df232) 에서 폰트 아틀라스 이미지의 크기를 수정했습니다.
> 
> 아래 링크에서 해당 수정 사항이 적용된 리소스 팩을 내려받으실 수 있습니다.
> https://github.com/yf-dev/majsoul-plus-korean/releases/tag/3.0.20200728151609
> 
> 아마도 해당 이슈가 해결됬을 것 같은데, 확인 부탁드립니다.

네 정말 수고하셨습니다. 감사합니다. 해당 이슈는 해결된 것으로 보입니다. 다른 이슈가 또 생길시 알려드리겠습니다.

**Comment by rishubil** [comment]
확인해주셔서 감사합니다.
문제가 해결되었으므로, 이 이슈를 닫습니다.
