### ISSUE TITLE
atlas 질문

### ISSUE THREAD

**Issue by Shinjjanggu** [yf-dev/majsoul-plus-korean#19]
[-] Pack test\lobby.atlas_unpack...
max_size = 1024
target_size = 2048
lobby.png
lobby1.png

lobby.png만 생성되서
5시간동안 이것저것 찾아보니
원본보다 사이즈가 크면 자동으로 2048로 확장하는 듯 한데
혹시 원본사이즈 그대로 출력하는 방법은 없을까염...

**Comment by rishubil** [comment]
현재는 코드를 수정하는 방법 외의 별도 옵션을 제공하지 않습니다.

솔직히 말씀드리면, 그런 기능이 필요한 이유를 잘 모르겠습니다.

혹시 괜찮으시다면 사용 용도를 알 수 있을까요?

**Comment by Shinjjanggu** [comment]
아 죄송해요 글쓸때는 2048*2048로 늘어나있고 코드엔 complete가 있는데 메세지가 안보여서 작동 안되는 줄 알았어요 ㅜㅠ 작동 되네요 감사합니당

**Comment by rishubil** [comment]
별 문제가 없다니 다행이네요.
이 이슈는 닫겠습니다.

추가 문의사항이 있으시다면 이 이슈를 다시 여시거나 새로운 이슈를 열어주세요.

**Comment by Shinjjanggu** [comment]
감사합니당
