### ISSUE TITLE
폰트 문제상황의 사진을 올려드리겠습니다.

### ISSUE THREAD

**Issue by op06072** [yf-dev/majsoul-plus-korean#20]
![Screenshot_20200728-001617_Samsung Internet.jpg](https://user-images.githubusercontent.com/60420877/88616061-1d33dd00-d0ce-11ea-94c9-21f5b64839c7.jpg)
![Screenshot_20200727-235812_Samsung Internet.jpg](https://user-images.githubusercontent.com/60420877/88616108-3472ca80-d0ce-11ea-928d-e6e6c6d1fdf2.jpg)![Screenshot_20200727-233237_Samsung Internet.jpg](https://user-images.githubusercontent.com/60420877/88616117-3f2d5f80-d0ce-11ea-8378-1894cf1676d7.jpg)
이런식으로 폰트이슈가 발생합니다. 작혼플러스를 컴에 구동하고 koa서버로 돌고있는 작혼에 컴의 ip주소를 이용해 접속한 것입니다.

**Comment by rishubil** [comment]
#18 에서 말씀하셨던 이슈에 연장선인 것 같습니다.

이 이슈는 닫고, 기존 이슈에서 계속 논의하는 것이 좋을 것 같습니다.

**Comment by op06072** [comment]
> #18 에서 말씀하셨던 이슈에 연장선인 것 같습니다.
> 
> 이 이슈는 닫고, 기존 이슈에서 계속 논의하는 것이 좋을 것 같습니다.

그럼 위 해당 사진을 해당 이슈에 다시 올릴까요?

**Comment by rishubil** [comment]
제가 다시 올려두었으니 신경쓰지 않으셔도 될 것 같습니다.
