### ISSUE TITLE
CORS 오류로 실행이 안됩니다.

### ISSUE THREAD

**Issue by MMMany** [yf-dev/majsoul-plus-korean#32]
안녕하세요.
글로벌 서버에서 본 한글패치를 적용해서 즐기려고 하니 resource 다운로드 중에 CORS 오류로 동작이 안됩니다.

1) 크롬 브라우저 (99.0.4844.51)
2) Tampermonkey
3) Majsoul Korean (EN Server) 스크립트, 0.1.6

크롬 콘솔에서 확인한 에러 로그도 같이 첨부드립니다.
[mahjongsoul.game.yo-star.com-1647814644539.log](https://github.com/yf-dev/majsoul-plus-korean/files/8312284/mahjongsoul.game.yo-star.com-1647814644539.log)

**Comment by rishubil** [comment]
해당 이슈는 https://github.com/yf-dev/majsoul-korean-resources/ 의 이슈입니다.
https://github.com/yf-dev/majsoul-korean-resources/issues/2 로 해당 이슈를 옮깁니다.
